import os
import sqlite3
from fastapi import FastAPI
from fastapi.responses import FileResponse, Response
from fastapi.middleware.cors import CORSMiddleware

app = FastAPI(title="Bastion WAF Admin Control Panel")

# Enable CORS so the dashboard frontend can query endpoints smoothly
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Resolve path to the SQLite database generated by the WAF proxy
DB_PATH = os.path.abspath(os.path.join(os.path.dirname(__file__), "database", "waf.db"))


def get_db_connection():
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    return conn


# API Endpoint: Retrieve recent traffic and security events
@app.get("/api/logs")
async def get_logs():
    if not os.path.exists(DB_PATH):
        return []
    try:
        conn = get_db_connection()
        cursor = conn.cursor()
        # Query logs from database table
        cursor.execute("SELECT * FROM events ORDER BY id DESC LIMIT 50")
        rows = cursor.fetchall()
        conn.close()
        return [dict(row) for row in rows]
    except Exception as e:
        return {"error": str(e)}


# API Endpoint: Retrieve summary metrics (Total, Blocked, Clean)
@app.get("/api/stats")
async def get_stats():
    if not os.path.exists(DB_PATH):
        return {"total": 0, "blocked": 0, "allowed": 0}
    try:
        conn = get_db_connection()
        cursor = conn.cursor()
        cursor.execute(
            "SELECT COUNT(*) as total, SUM(CASE WHEN blocked = 1 THEN 1 ELSE 0 END) as blocked FROM events"
        )
        row = cursor.fetchone()
        conn.close()

        total = row["total"] if row and row["total"] else 0
        blocked = row["blocked"] if row and row["blocked"] else 0
        return {"total": total, "blocked": blocked, "allowed": total - blocked}
    except Exception as e:
        return {"total": 0, "blocked": 0, "allowed": 0, "error": str(e)}


# Web Route: Serve Dashboard Interface
@app.get("/")
@app.get("/{path:path}")
async def serve_dashboard(path: str = ""):
    dashboard_path = os.path.abspath(
        os.path.join(os.path.dirname(__file__), "dashboard", "index.html")
    )
    if os.path.exists(dashboard_path):
        return FileResponse(dashboard_path)
    return Response(
        content='{"error": "Dashboard UI file not found"}',
        status_code=404,
        media_type="application/json",
    )